# Generated by Django 5.2.8 on 2026-09-16 00:21

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("patients", "0003_alter_patient_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancerCase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True,
                        help_text="ICD-O-3 morphology + ICD-10 topography",
                        max_length=64,
                    ),
                ),
                ("diagnosis_text", models.TextField(blank=True)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("tnm_t", models.CharField(blank=True, max_length=8)),
                ("tnm_n", models.CharField(blank=True, max_length=8)),
                ("tnm_m", models.CharField(blank=True, max_length=8)),
                (
                    "stage",
                    models.CharField(
                        blank=True, help_text="I, II, III, IV, or empty if unknown", max_length=8
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("new", "New"),
                            ("diagnostic", "Diagnostic"),
                            ("consilium", "Consilium"),
                            ("waiting_hospitalization", "Waiting for hospitalization"),
                            ("in_treatment", "In treatment"),
                            ("observation", "Observation"),
                            ("remission", "Remission"),
                            ("relapse", "Relapse"),
                            ("terminal", "Terminal"),
                        ],
                        default="new",
                        max_length=32,
                        protected=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="accounts.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="cases_cance_organiz_63b8f6_idx"
                    ),
                    models.Index(
                        fields=["patient", "created_at"], name="cases_cance_patient_8e6b13_idx"
                    ),
                ],
            },
        ),
    ]
