# Generated by Django 5.2.8 on 2026-09-23 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_statustransition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statustransition",
            name="transitioned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
