# Generated by Django 5.2.8 on 2026-09-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_alter_statustransition_transitioned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancercase",
            name="icd11_mms_uri",
            field=models.CharField(
                blank=True, db_index=True, help_text="ICD-11 MMS entity URI", max_length=255
            ),
        ),
    ]
