# Generated by Django 5.2.8 on 2026-09-30 02:31

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_cancercase_icd11_mms_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancercase",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("new", "New"),
                    ("diagnostic", "Diagnostic"),
                    ("consilium", "Consilium"),
                    ("waiting_hospitalization", "Waiting for hospitalization"),
                    ("admission_refused", "Admission refused"),
                    ("in_treatment", "In treatment"),
                    ("observation", "Observation"),
                    ("remission", "Remission"),
                    ("relapse", "Relapse"),
                    ("terminal", "Terminal"),
                ],
                default="new",
                max_length=32,
                protected=True,
            ),
        ),
    ]
