# Generated by Django 5.2.8 on 2026-09-21 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cases", "0002_statustransition"),
        ("events", "0005_eventtreatment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lab", "Laboratory test"),
                            ("histology", "Histology"),
                            ("cytology", "Cytology"),
                            ("imaging", "Imaging"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=16,
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Short description, e.g. 'CT chest with contrast'",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "result_text",
                    models.TextField(
                        blank=True, help_text="Result of the procedure (free text in MVP)"
                    ),
                ),
                ("result_received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="cases.cancercase",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The event during which the referral was issued",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="events.event",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_ordered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="referrals_r_organiz_f8c3a2_idx"
                    ),
                    models.Index(
                        fields=["case", "-ordered_at"], name="referrals_r_case_id_33948a_idx"
                    ),
                ],
            },
        ),
    ]
