# Generated by Django 5.2.8 on 2026-09-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("cases", "0004_cancercase_icd11_mms_uri"),
        ("events", "0005_eventtreatment"),
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The doctor who will perform the procedure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="room",
            field=models.CharField(blank=True, help_text="Room or cabinet number", max_length=32),
        ),
        migrations.AddField(
            model_name="referral",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True, help_text="Date and time when the procedure is scheduled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Short description, denormalized from method name",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lab", "Laboratory test"),
                    ("histology", "Histology"),
                    ("cytology", "Cytology"),
                    ("imaging", "Imaging"),
                    ("other", "Other"),
                ],
                help_text="Denormalized from department category for quick filters",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticDepartment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("laboratory", "Laboratory"),
                            ("pathology", "Pathology / Morphology"),
                            ("imaging", "Radiology / Imaging"),
                            ("endoscopy", "Endoscopy"),
                            ("functional", "Functional diagnostics"),
                            ("surgery", "Day surgery"),
                            ("molecular", "Molecular diagnostics"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_departments",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="The department performing the procedure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="referrals.diagnosticdepartment",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticMethod",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="Short code, e.g. 'CT', 'CBC'", max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="referrals.diagnosticdepartment",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="method",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific diagnostic method",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="referrals.diagnosticmethod",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["department", "status"], name="referrals_r_departm_f05071_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticdepartment",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_department_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticmethod",
            index=models.Index(
                fields=["department", "is_active"], name="referrals_d_departm_8ccf29_idx"
            ),
        ),
    ]
