# Generated by Django 5.2.8 on 2026-09-16 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cases", "0002_statustransition"),
        ("patients", "0003_alter_patient_contacts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary_visit", "Primary visit"),
                            ("followup_visit", "Follow-up visit"),
                            ("consilium", "Consilium"),
                            ("hospitalization", "Hospitalization"),
                            ("treatment", "Treatment"),
                            ("observation_visit", "Observation visit"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="cases.cancercase",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="accounts.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "scheduled_at"],
                        name="events_even_organiz_bc9b30_idx",
                    ),
                    models.Index(
                        fields=["case", "-scheduled_at"], name="events_even_case_id_aaa0f3_idx"
                    ),
                    models.Index(
                        fields=["patient", "-scheduled_at"], name="events_even_patient_b37ec1_idx"
                    ),
                ],
            },
        ),
    ]
