# Generated by Django 5.2.8 on 2026-09-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFollowupVisit",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "findings",
                    models.TextField(blank=True, help_text="Findings and test results reviewed"),
                ),
                ("plan", models.TextField(blank=True, help_text="Next steps and treatment plan")),
            ],
            options={
                "verbose_name": "Follow-up visit",
                "verbose_name_plural": "Follow-up visits",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="EventObservationVisit",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "findings",
                    models.TextField(blank=True, help_text="Findings from the observation visit"),
                ),
            ],
            options={
                "verbose_name": "Observation visit",
                "verbose_name_plural": "Observation visits",
            },
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="EventPrimaryVisit",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, help_text="Patient's complaints at presentation"),
                ),
                (
                    "physical_exam",
                    models.TextField(blank=True, help_text="Findings from physical examination"),
                ),
            ],
            options={
                "verbose_name": "Primary visit",
                "verbose_name_plural": "Primary visits",
            },
            bases=("events.event",),
        ),
    ]
