# Generated by Django 5.2.8 on 2026-09-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventfollowupvisit_eventobservationvisit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventConsilium",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "decision",
                    models.TextField(blank=True, help_text="Joint decision of the consilium"),
                ),
                (
                    "recommended_plan",
                    models.TextField(blank=True, help_text="Recommended treatment plan"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specialists who participated in the consilium",
                        related_name="consiliums_attended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consilium",
                "verbose_name_plural": "Consilia",
            },
            bases=("events.event",),
        ),
    ]
