# Generated by Django 5.2.8 on 2026-09-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventconsilium"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHospitalization",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        blank=True,
                        help_text="Ward or department (e.g. 'Oncology ward 3')",
                        max_length=128,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for hospitalization")),
                (
                    "discharge_date",
                    models.DateField(
                        blank=True, help_text="Date of discharge, if already discharged", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalization",
                "verbose_name_plural": "Hospitalizations",
            },
            bases=("events.event",),
        ),
    ]
