# Generated by Django 5.2.8 on 2026-09-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventhospitalization"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTreatment",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("chemo", "Chemotherapy"),
                            ("radiation", "Radiation therapy"),
                            ("surgery", "Surgery"),
                            ("targeted", "Targeted therapy"),
                            ("immunotherapy", "Immunotherapy"),
                            ("other", "Other"),
                        ],
                        default="chemo",
                        max_length=32,
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        blank=True, help_text="Regimen name (e.g. 'AC', 'FOLFOX')", max_length=128
                    ),
                ),
                (
                    "cycle_number",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Current cycle number (e.g. 3)", null=True
                    ),
                ),
                (
                    "cycle_total",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Total number of cycles in the course (e.g. 6)",
                        null=True,
                    ),
                ),
                ("drugs", models.TextField(blank=True, help_text="Drugs and doses (free text)")),
            ],
            options={
                "verbose_name": "Treatment",
                "verbose_name_plural": "Treatments",
            },
            bases=("events.event",),
        ),
    ]
