# Generated by Django 5.2.8 on 2026-09-22 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("download", "Download"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model name, e.g. 'Patient', 'CancerCase'", max_length=64
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Primary key of the object (null for lists)",
                        null=True,
                    ),
                ),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable representation at the time of the event",
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("request_method", models.CharField(blank=True, max_length=8)),
                ("request_path", models.CharField(blank=True, max_length=512)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null if anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "-timestamp"],
                        name="audit_audit_entity__771db8_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"], name="audit_audit_user_id_5d0160_idx"
                    ),
                    models.Index(
                        fields=["organization", "-timestamp"], name="audit_audit_organiz_c9cbc6_idx"
                    ),
                ],
            },
        ),
    ]
