# Generated by Django 5.1.4 on 2026-09-15 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("medical_record_number", models.CharField(max_length=64)),
                ("contacts", models.JSONField(blank=True, default=dict)),
                (
                    "vital_status",
                    models.CharField(
                        choices=[("alive", "Alive"), ("dead", "Dead")],
                        default="alive",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "full_name"], name="patients_pa_organiz_d8fe5e_idx"
                    ),
                    models.Index(
                        fields=["medical_record_number"], name="patients_pa_medical_ff50e5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "medical_record_number"),
                        name="unique_mrn_per_organization",
                    )
                ],
            },
        ),
    ]
