# Generated by Django 5.1.4 on 2026-09-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contacts",
            field=models.TextField(blank=True, default=""),
        ),
    ]
