# Generated by Django 5.2.8 on 2026-09-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contacts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
