# Generated by Django 5.2.8 on 2026-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="death_date",
            field=models.DateField(blank=True, help_text="Date of death, if applicable", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance_policy_number",
            field=models.CharField(
                blank=True,
                help_text="Insurance policy number (e.g. SNILS, NHS number, etc.)",
                max_length=64,
            ),
        ),
    ]
