# Generated by Django 5.2.8 on 2026-09-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosisCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "system",
                    models.CharField(
                        choices=[("icd10", "ICD-10"), ("icd_o_3", "ICD-O-3")],
                        default="icd10",
                        max_length=16,
                    ),
                ),
                ("code", models.CharField(db_index=True, help_text="e.g. 'C50.9'", max_length=16)),
                ("name", models.CharField(max_length=512)),
                ("name_en", models.CharField(blank=True, max_length=512)),
                ("chapter", models.CharField(blank=True, max_length=8)),
                ("block", models.CharField(blank=True, db_index=True, max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["system", "code"], name="dictionarie_system_bed5fa_idx"),
                    models.Index(fields=["system", "block"], name="dictionarie_system_0ecebb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code"), name="unique_code_per_system"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MorphologyCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="e.g. '8140/3'", max_length=16, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("name_en", models.CharField(blank=True, max_length=512)),
                (
                    "behavior",
                    models.CharField(
                        blank=True,
                        help_text="/0 benign, /1 uncertain, /2 in situ, /3 malignant, /6 metastatic",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [models.Index(fields=["code"], name="dictionarie_code_c62081_idx")],
            },
        ),
    ]
