# Generated by Django 5.2.8 on 2026-09-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundationEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. http://id.who.int/icd/entity/1047754165",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=1024)),
                ("definition", models.TextField(blank=True)),
                ("long_definition", models.TextField(blank=True)),
                (
                    "synonyms",
                    models.JSONField(blank=True, default=list, help_text="List of synonym strings"),
                ),
                ("parent_uris", models.JSONField(blank=True, default=list)),
                ("child_uris", models.JSONField(blank=True, default=list)),
                (
                    "exclusions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of {label, uri} dicts"
                    ),
                ),
                ("browser_url", models.URLField(blank=True, max_length=512)),
                ("chapter", models.CharField(blank=True, db_index=True, max_length=8)),
                ("last_synced_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Icd11SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("release_id", models.CharField(help_text="e.g. 2026-01", max_length=32)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("foundation_count", models.IntegerField(default=0)),
                ("mms_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MmsEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. http://id.who.int/icd/release/11/2026-01/mms/1047754165/unspecified",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "foundation_uri",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Link to the foundation entity",
                        max_length=255,
                    ),
                ),
                (
                    "the_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g. 2C6Z (may include postcoordination, e.g. 2E0Y&XA12C1)",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=1024)),
                ("chapter", models.CharField(blank=True, db_index=True, max_length=8)),
                ("is_leaf", models.BooleanField(default=False)),
                ("is_residual_unspecified", models.BooleanField(default=False)),
                ("is_residual_other", models.BooleanField(default=False)),
                ("parent_uris", models.JSONField(blank=True, default=list)),
                ("child_uris", models.JSONField(blank=True, default=list)),
                (
                    "synonyms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Synonym strings extracted from matchingPVs",
                    ),
                ),
                ("last_synced_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["the_code"],
            },
        ),
        migrations.DeleteModel(
            name="DiagnosisCode",
        ),
        migrations.DeleteModel(
            name="MorphologyCode",
        ),
        migrations.AddIndex(
            model_name="foundationentity",
            index=models.Index(fields=["title"], name="dictionarie_title_49ad31_idx"),
        ),
        migrations.AddIndex(
            model_name="foundationentity",
            index=models.Index(fields=["chapter"], name="dictionarie_chapter_aac30a_idx"),
        ),
        migrations.AddIndex(
            model_name="mmsentity",
            index=models.Index(fields=["the_code"], name="dictionarie_the_cod_813536_idx"),
        ),
        migrations.AddIndex(
            model_name="mmsentity",
            index=models.Index(fields=["chapter"], name="dictionarie_chapter_4edff4_idx"),
        ),
        migrations.AddIndex(
            model_name="mmsentity",
            index=models.Index(fields=["foundation_uri"], name="dictionarie_foundat_af9390_idx"),
        ),
    ]
