# Generated by Django 5.2.8 on 2026-09-21 08:00

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cases", "0002_statustransition"),
        ("events", "0005_eventtreatment"),
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("conclusion", "Conclusion"),
                            ("scan", "Scan"),
                            ("analysis", "Analysis"),
                            ("histology", "Histology"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Short description, e.g. 'CT chest report'",
                        max_length=255,
                    ),
                ),
                ("file", models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                (
                    "file_size",
                    models.PositiveIntegerField(blank=True, help_text="Size in bytes", null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.cancercase",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The event during which the document was attached",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="events.event",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="accounts.organization",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        help_text="The referral this document is a result of",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="referrals.referral",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-uploaded_at"],
                        name="documents_d_organiz_98e0b3_idx",
                    ),
                    models.Index(
                        fields=["case", "-uploaded_at"], name="documents_d_case_id_0bbc2c_idx"
                    ),
                ],
            },
        ),
    ]
